[context.production]
  publish = "out/"
  command = "yarn build"

[context.dev.environment]
  NODE_ENV = "development"

[[context.deploy-preview].environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"